export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS"
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS"
export const AUTH_FAIL = "AUTH_FAIL"
export const SET_LOADING = "SET_LOADING"
export const LOGOUT = "LOGOUT"
export const GET_AUTH_USER = "GET_AUTH_USER"
export const ADD_CART = "ADD_CART"
export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS';
export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD';






//products 

export const GET_PRODUCTS = "GET_PRODUCTS"
export const ADD_PRODUCTS = "ADD_PRODUCTS"